pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        gradlePluginPortal()
    }
}

rootProject.name = 'securetrade'

include 'common'
include 'forge'
include 'fabric'
